version: 2

defaults: &defaults 
  working_directory: ~/root
  docker:
    - image: circleci/node:8.10

jobs:

  build:
    <<: *defaults
    steps:
      - run:
          name: Install Code Climate test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

  sdk-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/root/tmp
      - run:
          name: Install web dependencies
          command: cd sdk && npm install
      - run:
          name: Run web tests
          command: | 
            cd sdk
            npm run coverage
            ../tmp/cc-test-reporter format-coverage -t lcov -o ../tmp/codeclimate.sdk.json --add-prefix sdk
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.sdk.json

  web-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/root/tmp
      - run:
          name: Install web dependencies
          command: cd web && npm install
      - run:
          name: Run web tests
          command: | 
            cd web
            npm run coverage
            ../tmp/cc-test-reporter format-coverage -t lcov -o ../tmp/codeclimate.web.json --add-prefix web
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.web.json

  desktop-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/root/tmp
      - run:
          name: Install desktop dependencies
          command: cd desktop && npm install
      - run:
          name: Run desktop tests
          command: | 
            cd desktop
            npm run coverage
            ../tmp/cc-test-reporter format-coverage -t lcov -o ../tmp/codeclimate.desktop.json --add-prefix desktop
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.desktop.json

  blockchain-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/root/tmp
      - run:
          name: Install blockchain dependencies
          command: cd blockchain && npm install
      - run:
          name: Run blockchain tests
          command: | 
            cd blockchain
            npm run coverage
            ../tmp/cc-test-reporter format-coverage -t lcov -o ../tmp/codeclimate.blockchain.json --add-prefix blockchain
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.blockchain.json

  cli-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/root/tmp
      - run:
          name: Install cli dependencies
          command: cd cli && npm install
      - run:
          name: Run cli tests
          command: | 
            cd cli
            npm run coverage
            ../tmp/cc-test-reporter format-coverage -t lcov -o ../tmp/codeclimate.cli.json --add-prefix cli
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.cli.json

  submit-coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/root/tmp
      - run:
          name: Upload combined coverage to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 5 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json

workflows:
  version: 2

  all:
    jobs:
      - build
      - blockchain-tests:
          requires:
            - build
      - cli-tests:
          requires:
            - build
      - desktop-tests:
          requires:
            - build
      - sdk-tests:
          requires:
            - build
      - web-tests:
          requires:
            - build
      - submit-coverage:
          requires:
            - blockchain-tests
            - cli-tests
            - desktop-tests
            - sdk-tests
            - web-tests
