name: platform
on:
  push:
    branches: [ master ]
jobs:

  setup:
    runs-on: "ubuntu-latest"
    name: Build platform
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: "React Stack"
      run: | 
        cd stacks/react
        npm ci
