name: platform
on:
  push:
    branches: [ master ]
jobs:

  setup:
    runs-on: "ubuntu-latest"
    name: Build platform
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: "Download CC Test Reporter"
      run: |
        mkdir -p tmp/
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
        chmod +x ./tmp/cc-test-reporter
    - name: "React Stack"
      run: | 
        cd stacks/react
        npm i
        npm run coverage